name: CI/CD Pipeline for Auth Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t $DOCKER_USERNAME/auth-service:latest .

    - name: Login to DockerHub
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Push Docker image to DockerHub
      run: |
        docker push $DOCKER_USERNAME/auth-service:latest

    - name: Trigger Deploy on Render
      run: |
        curl -X POST $RENDER_DEPLOY_HOOK
